### ISSUE TITLE
Enhancement Auth Pages

### ISSUE THREAD

**Issue by PenDZ-Alter** [PenDZ-Alter/kel7_mobile#25]
Tasks : 

- [x] Add Login Page
- [x] Add Register Page
- [x] Setup Backend Data

**Comment by PenDZ-Alter** [comment]
Maybe, we should export api variables to another pages?

**Comment by Ditto-Prasetyo** [comment]
Yup

**Comment by PenDZ-Alter** [comment]
Login already setted up in #36

**Comment by PenDZ-Alter** [comment]
All resolve and fixed in #42
