### ISSUE TITLE
Enhancement Design Apps

### ISSUE THREAD

**Issue by PenDZ-Alter** [PenDZ-Alter/kel7_mobile#27]
Tasks : 

- [x] Design Login Page
- [x] Design Register Page
- [x] Design Dashboard
- [x] Design Fakultas Page
- [x] Design Prodi Page
- [x] Design Tracer Alumni Page
- [x] Add Splash Screen
- [x] Change Modal forms into Form Page
- [x] Design Form Page
- [x] Design Splash Screen
- [x] Design Login Screen
- [x] Design Register Screen
- [x] Register Screen Functionality
- [x] Add details on every list item

**Comment by PenDZ-Alter** [comment]
There's problems with loading progress looping in Fakultas Page

**Comment by Ditto-Prasetyo** [comment]
Okay

**Comment by Ditto-Prasetyo** [comment]
I'll fix the design of Tracer Alumni Page, add the design on the Tracer Alumni Page and the splash screen

**Comment by Ditto-Prasetyo** [comment]
Improve design at #41

**Comment by Ditto-Prasetyo** [comment]
Done
